name: Run Colab Notebook Daily

on:
  schedule:
     - cron: '0 4 * * *'   # Runs every day at 4:00 AM UTC
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Jupyter
        run: pip install notebook nbconvert

      - name: Execute notebook
        run: |
          jupyter nbconvert --execute --to notebook --inplace air-nuggets.ipynb
